var personName = "Fouzia Bibi";
console.log("Hello,".concat(personName, ",Would you like to learn some python today"));
var person_name = "fouzia Bibi";
console.log(person_name.toLowerCase());
console.log(person_name.toUpperCase());
console.log(person_name.charAt(0).toUpperCase() + person_name.slice(1));
console.log('Nelson Mondela once said,"A Winner is a dreamer who never give up"');
var famous_person = 'Nelson Mondela';
var quote = 'Education is the Most powerful weapon which you can use to change the world';
console.log("".concat(famous_person, " Once said,\"").concat(quote, "\""));
